### ISSUE TITLE
Adding to Conda-forge

### ISSUE THREAD

**Issue by cheginit** [MaartenGr/BERTopic#242]
Is there any plan to add BERTopic to the `conda-forge` repository? If interested, I can help with the process.

**Comment by MaartenGr** [comment]
Currently, there aren't any plans for adding BERTopic to the conda-forge repo. Thus far I have not had any other requests but I might add the request to the roadmap if there are many that would like to have this "feature". Thank you for offering to help with the process though!

**Comment by cheginit** [comment]
Sure, hopefully there will be more.

**Comment by cheginit** [comment]
This is a working `meta.yml` that I generated for `bertopic` for packaging (az 1*.bz2` archive and installing it with `conda`:

```yaml
{% set name = "bertopic" %}
{% set version = "0.9.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/bertopic-{{ version }}.tar.gz
  sha256: 2995f2dea61c9c8170d71d1a0581b44c9d318163f96067dbf947d7f6720c3ef2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - hdbscan >=0.8.27
    - numpy >=1.20.0
    - pandas >=1.1.5
    - plotly >=4.7.0,<4.14.3
    - python =3.8
    - scikit-learn >=0.22.2.post1
    - sentence-transformers >=0.4.1
    - tqdm >=4.41.1
    - umap-learn >=0.5.0
    - sentencepiece
    - torchvision >=0.10
    - pytorch >=1.9
    - cython
    - gensim >=3.6.0

test:
  imports:
    - bertopic
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/MaartenGr/BERTopic
  summary: BERTopic performs topic Modeling with state-of-the-art transformer models.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cheginit
```
